Girilen sayının tek veya çift olduğunu tespit eden program

In [ ]:
#sayı = Sayı almamız lazım
#mod değeri = sayı mod 2
#Eğer mod 0sa 
#   çift
#Değilse
#   tek
sayi = int(input("Ekrandan bir sayı giriniz"))  
mod_degeri = sayi % 2
if mod_degeri == 0:
    print("Çift")
else:
    print("Tek")

Bir sayının mutlak değerini alıp ekrana gösteren program

In [ ]:
sayi = int(input("Ekrandan bir sayı giriniz"))  
if sayi<0:#Eğer 0'dan küçükse
    sayi *= -1 #-1 ile çarparız
    print(sayi)
else:#Değilse
    print(sayi)#aynen yazdır

In [ ]:
sayi = int(input("Ekrandan bir sayı giriniz"))  
if sayi<0:#Eğer 0'dan küçükse
    sayi *= -1 #-1 ile çarparız
print(sayi)

BMI hesabı yapan program

In [ ]:
boy = float(input("Boy giriniz (m)"))#boy almam lazım (m)
kilo = float(input("Kilo giriniz"))#kilo almam lazım (kg)
bmi = kilo / pow(boy,2)  #bmi kilo / boy ^ 2
print(bmi)
if bmi < 18.5:              #Eğer bmi < 18.5
    print("Düşük")          #Düşük kilo
if bmi >= 18.5 and bmi < 25: #Değil de bmi < 25
    print("Normal")         #Normal
if bmi >= 25 and bmi < 30:   #Değil de bmi < 30
    print("Yüksek")         #Yüksek kilo
else:                       #Değilse
    print("...")            #Çok yüksek


In [ ]:
boy = float(input("Boy giriniz (m)"))#boy almam lazım (m)
kilo = float(input("Kilo giriniz"))#kilo almam lazım (kg)
bmi = kilo / pow(boy,2)  #bmi kilo / boy ^ 2
print(bmi)
if bmi < 18.5:              #Eğer bmi < 18.5
    print("Düşük")          #Düşük kilo
elif bmi < 25:              #Değil de bmi < 25
    print("Normal")         #Normal
elif bmi < 30:              #Değil de bmi < 30
    print("Yüksek")         #Yüksek kilo
else:                       #Değilse
    print("...")            #Çok yüksek

Bir mağaza için sipariş tutarı ve kg değerleri ekrandan girilecek ve kg başına 1 tl kargo ücreti fiyata eklenip gösterilecektir. Bu tutar kargo hariç 100 TL’nin üstündeyse kargo ücreti hesaplanmayacaktır.  Ayrıca tutar 200 TL’nin üzerinde ise toplam fiyata %10 indirim uygulanacaktır. 

In [22]:
siparis_tutari = float(input("Sipariş tutarı"))
kilogram = float(input("Kilogram"))
if siparis_tutari<100:                  #Eğer sipariş tutarı 100'den küçükse
    siparis_tutari += kilogram          #kg başına kargo ücreti hesapla sipariş tutarına ekle

if siparis_tutari > 200:                #Eğer toplam 200'den büyükse
    siparis_tutari *= 0.9               #sipariş tutarı üzerine %10 indirim uygula
    
print(siparis_tutari)                   #Toplam tutarı göster

261.0


In [ ]:
liste = []
print(liste)
liste = [1,2,3,4,5]
print(liste)

liste = [range(10),20,30]
print(liste)

liste = list(range(10))
print(liste)

liste = [i*2 for i in range(10)]
print(liste)

liste = []
for i in range(10):
    liste.append(i*2)
print(liste)


[]
[1, 2, 3, 4, 5]
[range(0, 10), 20, 30]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [33]:
liste = [10,20,30,40,50,60,70,80,90,100]
print(liste[3])
liste[3] = 70
print(liste)

40
[10, 20, 30, 70, 50, 60, 70, 80, 90, 100]


In [34]:
liste = [1,2,3,4,5,6,7,8,9,10]
indis = 5
print(liste[indis])

6


In [54]:
liste[indis] = liste[indis] + 1
print(liste)

[1, 2, 3, 4, 5, 26, 7, 8, 9, 10]


In [55]:
liste[indis+1]+= 2
print(liste)

[1, 2, 3, 4, 5, 26, 9, 8, 9, 10]


In [56]:
liste = [1,2,3,4,5,6,7,8,9,10]
print(liste[1:3])

[2, 3]


In [57]:
print(liste[1:8:2])

[2, 4, 6, 8]


In [58]:
print(liste[4:0:-1])

[5, 4, 3, 2]


In [ ]:
print(liste[:4])

[1, 2, 3, 4]


In [ ]:
print(liste[7:])

In [61]:
liste = [1,2,3,4,5,6,7,8,9,10]
liste += [5]
print(liste)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 5]


In [62]:
liste = [1,2,3,4,5,6,7,8,9,10]
liste += [5,5,7,8]
print(liste)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 5, 5, 7, 8]


In [63]:
liste = [1,2,3,4,5,6,7,8,9,10]
liste.append(5)
print(liste)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 5]


In [64]:
liste = [1,2,3,4,5,6,7,8,9,10]
liste.insert(3,5)
print(liste)

[1, 2, 3, 5, 4, 5, 6, 7, 8, 9, 10]


In [74]:
liste1 = [1,2,3]
liste2 = [4,5,6]
liste3 = [7,8,9]
liste = [liste1,liste2,liste3]
print(liste)
import numpy as np
matris = np.array(liste)
print(matris)
matris *=3
print(matris)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [ ]:
a=10
b=20
paket = b,a
print(paket)
x,y = paket
print(x,y)

(20, 10)
20 10


In [80]:
metin = "abc"
metin.replace("a","e")
print(metin)

abc


Kullanıcıdan girilen 10 değerin ortalamasını ve varyansını bulan uygulamayı yazınız.


In [ ]:
liste = [7,33,20,11,6,50,81,100,88,655]
toplam = 0
for eleman in liste:
    toplam += eleman
ortalama = toplam / len(liste)
print(ortalama)

toplam = 0
for eleman in liste:
    toplam += pow(ortalama - eleman,2)

varyans = toplam / len(liste)
print(varyans)

import numpy as np
print(np.mean(liste))
print(np.var(liste))

105.1
34706.49
105.1
34706.49
